name: CI
on:
  push:
    branches: [main]

jobs:
  run_eslint:
    name: Run ESLint
    strategy:
      matrix:
        node: ["12.22.0"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Packages
      run: npm install
    - name: Test
      run: node index.js
